name: CI

on:
  push:
    branches: [ main, task-1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install TA-Lib dependencies
        # TA-Lib requires libtool, automake, autoconf, and build-essential for compilation.
        # This setup ensures it can be installed from source on the GitHub Actions runner.
        run: |
         sudo apt-get update
         sudo apt-get install -y build-essential libtool automake autoconf
         wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
         tar -xvf ta-lib-0.4.0-src.tar.gz
         cd ta-lib && ./configure --prefix=/usr && make && sudo make install

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Install production dependencies and testing framework (pytest)
          pip install -r requirements.txt pytest
          
      - name: Run Unit Tests
        # Now we execute all tests in the 'tests/' directory
        run: |
          pytest tests/